#! /bin/bash
# generate-interface.sh generates the interface for the Payments contract

set -euo pipefail

OUTPUT_PATH=src/interfaces/IPayments.sol
ABI_TO_SOL_VERSION="0.8.0"
SOLIDITY_VERSION="^0.8.27"

# Check for required tools
for cmd in forge jq npx; do
  if ! command -v $cmd &> /dev/null; then
    echo "Error: '$cmd' is not installed or not in PATH." >&2
    exit 1
  fi
done

# Build the contracts
echo "Building contracts..."
forge build --force

# Create dir if it doesn't exist
mkdir -p "$(dirname "$OUTPUT_PATH")"

# Extract ABI using jq
echo "Generating interface at $OUTPUT_PATH..."
jq '.abi' out/Payments.sol/Payments.json | npx abi-to-sol@"$ABI_TO_SOL_VERSION" IPayments --license MIT --solidity-version "$SOLIDITY_VERSION" > "$OUTPUT_PATH"

# Remove ABI comments from the generated file
if [[ "$(uname)" == "Darwin" ]]; then
  sed -i '' '/^\/\/ THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:/,/^\*\//d' "$OUTPUT_PATH"
  sed -i '' 's/SEE SOURCE BELOW\. *!!/!!/' "$OUTPUT_PATH"
else
  sed -i '/^\/\/ THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:/,/^\*\//d' "$OUTPUT_PATH"
  sed -i 's/SEE SOURCE BELOW\. *!!/!!/' "$OUTPUT_PATH"
fi

echo "Interface generated at $OUTPUT_PATH"

forge fmt "$OUTPUT_PATH"