name: Solidity Contract Size Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check_contract_size:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v0.3.0
      
      - name: Install Dependencies
        run: forge install

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Ensure script is executable
        run: chmod +x .github/scripts/check-contract-size.sh

      - name: Check contract size
        run: .github/scripts/check-contract-size.sh
