name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v0.3.0

      - name: Install Dependencies
        run: |
          forge install

      - name: Add foundry to the PATH
        run: |
          echo "$HOME/.config/.foundry/bin" >> "$GITHUB_PATH"

      - name: Run build
        run: |
          make build

      - name: Run tests
        run: |
          make test
